export const array: any[] = [
    {
        check: false,
        name: '이지 시그너스',
        meso: 5059464,
        src: 'https://i.namu.wiki/i/xy1onLF2Eh3QsHM1hGbowtATA3XFLNDua8oGrIu1YQbrAQYAnNyycWVJymqpH9TNle09BNPJBBkNwaNXf1PSXQ.webp',
        hard: false,
        difficulty: 'EASY',
    },
    {
        check: false,
        name: '하드 힐라',
        meso: 6390000,
        src: 'https://i.namu.wiki/i/xkAv49nm21rPWT5mpuFDGBF2S0gc70tqMLTVyKj1qNNmaVPpjBOceuqlc9rsvQJFlh4mFGbPgaZqBun5vrOQtQ.webp',
        hard: false,
        difficulty: 'HARD',
    },
    {
        check: false,
        name: '카오스 핑크빈',
        meso: 7310000,
        src: 'https://i.namu.wiki/i/wqDvuAFvinyQZnJ5n9vwvsaT_ZWzUbVACT3jyExnO2aCnMpSvjoLQqad49NjfY85CCJXdpK1L53tqzAADsZRWw.webp',
        hard: false,
        difficulty: 'CHAOS',
    },
    {
        check: false,
        name: '노말 시그너스',
        meso: 8330000,
        src: 'https://i.namu.wiki/i/xy1onLF2Eh3QsHM1hGbowtATA3XFLNDua8oGrIu1YQbrAQYAnNyycWVJymqpH9TNle09BNPJBBkNwaNXf1PSXQ.webp',
        hard: false,
        difficulty: 'NORMAL',
    },
    {
        check: false,
        name: '카오스 자쿰',
        meso: 8980000,
        src: 'https://i.namu.wiki/i/KfsxkSC6DkvaKBQ22PHPc6pcMvObwSDp-mkwgSdL99Vw4OYHlfUKOGSQGKUJQoAo8ahSp3Kc9bO2RxcEkXtWUQ.webp',
        hard: false,
        difficulty: 'CHAOS',
    },
    {
        check: false,
        name: '카오스 피에르',
        meso: 9080000,
        src: 'https://i.namu.wiki/i/rRii1UpBFsO4y3MefnlY0QwuXeOpXK5dCV5h6Jq5pvb77SuF28VrsSMMSyFU6NWaQITnd6WWEETGKO8n8monIg.webp',
        hard: false,
        difficulty: 'CHAOS',
    },
    {
        check: false,
        name: '카오스 반반',
        meso: 9060000,
        src: 'https://i.namu.wiki/i/-VtxcgwbCe3C1hIr86TSKjjHDZfMquc8WG5sXQLJhGAzH_A6p_mml--2BLqK6v0aMS17F97JqIrhWxvWSjJx-g.webp',
        hard: false,
        difficulty: 'CHAOS',
    },
    {
        check: false,
        name: '카오스 블러디퀸',
        meso: 9040000,
        src: 'https://i.namu.wiki/i/zGHR27yvbeM4WJfRc1aRRTJD6t9G1Hs3Sr4U9p9P_mgbSBltqAAeydZwcogLq8XRHULHAz8uKfyyHaniucblOA.webp',
        hard: false,
        difficulty: 'CHAOS',
    },
    {
        check: false,
        name: '카오스 벨룸',
        meso: 11600000,
        src: 'https://i.namu.wiki/i/XWlfIMMZZSKby5FyBZ2UmL82I9Fl6iXpiP_CejECSHdwh3Abkflw2K9Pgp-M_TUJTTCS6EPeaO87iB6t5gXBeQ.webp',
        hard: false,
        difficulty: 'CHAOS',
    },
    {
        check: false,
        name: '하드 매그너스',
        meso: 10700000,
        src: 'https://i.namu.wiki/i/8IEIsgJYENvHw463fs7pTt8qwivTcj5kAF6LFH8FvtaHnqPQ1THyQjMqHs-nM4xogLApg-CTAbshZ9USFU3DyQ.webp',
        hard: false,
        difficulty: 'HARD',
    },
    {
        check: false,
        name: '카오스 파풀라투스',
        meso: 24700000,
        src: 'https://i.namu.wiki/i/-suBIbDeVJhzTkhXF8bNoVzCMcICvABpUmJ8DJcziBOJ2VLSaGy6DNDbMOIfsRYDsq1xinh7jJjoH2t1aS1l7Q.webp',
        hard: false,
        difficulty: 'CHAOS',
    },
    {
        check: false,
        name: '노말 스우',
        meso: 31400000,
        src: 'https://i.namu.wiki/i/ruflnxOS_pahmLa1F5ZGd0fGMayv2-2OeUsoE1f9amaqSvEabumApKDwKYiOtV1caYUhxrZ-glhPQ2cPC8ICPw.webp',
        hard: false,
        difficulty: 'NORMAL',
    },
    {
        check: false,
        name: '노말 데미안',
        meso: 32900000,
        src: 'https://i.namu.wiki/i/dKLZC6dsM7hb1BnKvHm_9hsL9C_tTp890DxsFrJ95CBu64wzhp7Bw_qY8kFvO-1cpoiAUiFuWKCmvlEUkoDMpg.webp',
        hard: false,
        difficulty: 'NORMAL',
    },
    {
        check: false,
        name: '노말 가디언 엔젤 슬라임',
        meso: 47800000,
        src: 'https://i.namu.wiki/i/NfyVXe5x1GSgN3ItCXYnMby76jSOjawGeKHZbCgkHLlx_0etsQmi-SBVPbfWaRxmnHZWio8z5XalVLb01O-jkg.webp',
        hard: false,
        difficulty: 'NORMAL',
    },
    {
        check: false,
        name: '이지 루시드',
        meso: 49000000,
        src: 'https://i.namu.wiki/i/EX4mog9TVN7S0SlVKzLnDqUu1w2ymmpdEkgU4seIKdcVtKBOqx31uIQ8-Dg1TPmpoV1uPGqyDPFEDuWiUEezKQ.webp',
        hard: false,
        difficulty: 'EASY',
    },
    {
        check: false,
        name: '이지 윌',
        meso: 53100000,
        src: 'https://i.namu.wiki/i/f1qnRIpp0_pOjczEjEZt2mauZ7XE8RUqD3AD14w3PFiPDc-QHlkE6qVpKdrgPtBzfImPw5cl1mp-y6Lu5Uw8MQ.webp',
        hard: false,
        difficulty: 'EASY',
    },
    {
        check: false,
        name: '노말 루시드',
        meso: 58600000,
        src: 'https://i.namu.wiki/i/EX4mog9TVN7S0SlVKzLnDqUu1w2ymmpdEkgU4seIKdcVtKBOqx31uIQ8-Dg1TPmpoV1uPGqyDPFEDuWiUEezKQ.webp',
        hard: false,
        difficulty: 'NORMAL',
    },
    {
        check: false,
        name: '노말 윌',
        meso: 67600000,
        src: 'https://i.namu.wiki/i/f1qnRIpp0_pOjczEjEZt2mauZ7XE8RUqD3AD14w3PFiPDc-QHlkE6qVpKdrgPtBzfImPw5cl1mp-y6Lu5Uw8MQ.webp',
        hard: false,
        difficulty: 'NORMAL',
    },
    {
        check: false,
        name: '노말 더스크',
        meso: 72400000,
        src: 'https://i.namu.wiki/i/4eyeZXwJ1wnQwpm47kvf3o8JklnpjeyJA_bKlqOjMTPP1IDDD-FlAcbhUO1zueTwmZWA0yKFV2nQPv1T24jbCQ.webp',
        hard: false,
        difficulty: 'NORMAL',
    },
    {
        check: false,
        name: '노말 듄켈',
        meso: 78100000,
        src: 'https://i.namu.wiki/i/Z2T13QUo0lfUtzcX5BH_0PQtp0Y7_jy8dFlzNyVLgReXrZRbtWjSssmEyi6-hrbN7XP5oJegXlmt7goyA5Jdzg.webp',
        hard: false,
        difficulty: 'NORMAL',
    },
    {
        check: false,
        name: '하드 데미안',
        meso: 113000000,
        src: 'https://i.namu.wiki/i/dKLZC6dsM7hb1BnKvHm_9hsL9C_tTp890DxsFrJ95CBu64wzhp7Bw_qY8kFvO-1cpoiAUiFuWKCmvlEUkoDMpg.webp',
        hard: true,
        difficulty: 'HARD',
    },
    {
        check: false,
        name: '하드 스우',
        meso: 119000000,
        src: 'https://i.namu.wiki/i/ruflnxOS_pahmLa1F5ZGd0fGMayv2-2OeUsoE1f9amaqSvEabumApKDwKYiOtV1caYUhxrZ-glhPQ2cPC8ICPw.webp',
        hard: true,
        difficulty: 'HARD',
    },
    {
        check: false,
        name: '하드 루시드',
        meso: 135000000,
        src: 'https://i.namu.wiki/i/EX4mog9TVN7S0SlVKzLnDqUu1w2ymmpdEkgU4seIKdcVtKBOqx31uIQ8-Dg1TPmpoV1uPGqyDPFEDuWiUEezKQ.webp',
        hard: true,
        difficulty: 'HARD',
    },
    {
        check: false,
        name: '하드 윌',
        meso: 165000000,
        src: 'https://i.namu.wiki/i/f1qnRIpp0_pOjczEjEZt2mauZ7XE8RUqD3AD14w3PFiPDc-QHlkE6qVpKdrgPtBzfImPw5cl1mp-y6Lu5Uw8MQ.webp',
        hard: true,
        difficulty: 'HARD',
    },
    {
        check: false,
        name: '노말 진 힐라',
        meso: 153000000,
        src: 'https://i.namu.wiki/i/tEUqjqEdPq18JmCb4wQqUp8_VSrf3XuvGNyyCqTH-LQQhjt-wQQXuib7SY-eERKUr8FfBCm58NW35gDN7Ra0dg.webp',
        hard: true,
        difficulty: 'NORMAL',
    },
    {
        check: false,
        name: '카오스 가디언 엔젤 슬라임',
        meso: 161000000,
        src: 'https://i.namu.wiki/i/NfyVXe5x1GSgN3ItCXYnMby76jSOjawGeKHZbCgkHLlx_0etsQmi-SBVPbfWaRxmnHZWio8z5XalVLb01O-jkg.webp',
        hard: true,
        difficulty: 'CHAOS',
    },
    {
        check: false,
        name: '카오스 더스크',
        meso: 150000000,
        src: 'https://i.namu.wiki/i/4eyeZXwJ1wnQwpm47kvf3o8JklnpjeyJA_bKlqOjMTPP1IDDD-FlAcbhUO1zueTwmZWA0yKFV2nQPv1T24jbCQ.webp',
        hard: true,
        difficulty: 'CHAOS',
    },
    {
        check: false,
        name: '하드 듄켈',
        meso: 177000000,
        src: 'https://i.namu.wiki/i/Z2T13QUo0lfUtzcX5BH_0PQtp0Y7_jy8dFlzNyVLgReXrZRbtWjSssmEyi6-hrbN7XP5oJegXlmt7goyA5Jdzg.webp',
        hard: true,
        difficulty: 'HARD',
    },
    {
        check: false,
        name: '하드 진 힐라',
        meso: 200000000,
        src: 'https://i.namu.wiki/i/tEUqjqEdPq18JmCb4wQqUp8_VSrf3XuvGNyyCqTH-LQQhjt-wQQXuib7SY-eERKUr8FfBCm58NW35gDN7Ra0dg.webp',
        hard: true,
        difficulty: 'HARD',
    },
    {
        check: false,
        name: '노말 선택받은 세렌',
        meso: 220000000,
        src: 'https://i.namu.wiki/i/DhzPskFnaHWVTfJk_Tb0GDDk7YWU8g-MS9IEau0kC03K7BKdFeZPheFglgLazh_9UuVj_jcaLdEH1L5dmM1jfQ.webp',
        hard: true,
        difficulty: 'NORMAL',
    },
    {
        check: false,
        name: '하드 선택받은 세렌',
        meso: 325000000,
        src: 'https://i.namu.wiki/i/DhzPskFnaHWVTfJk_Tb0GDDk7YWU8g-MS9IEau0kC03K7BKdFeZPheFglgLazh_9UuVj_jcaLdEH1L5dmM1jfQ.webp',
        hard: true,
        difficulty: 'HARD',
    },
    {
        check: false,
        name: '이지 감시자 칼로스',
        meso: 265000000,
        src: 'https://i.namu.wiki/i/XKVybiizrvprkaLQltvNf3XfqPB1BSn1ItKV6ijJsIliqxdZCKeqmSQNQKWwGCkM6ZwJDKe7luq9plx6gDpAzg.webp',
        hard: true,
        difficulty: 'EASY',
    },
    {
        check: false,
        name: '노말 감시자 칼로스',
        meso: 364000000,
        src: 'https://i.namu.wiki/i/XKVybiizrvprkaLQltvNf3XfqPB1BSn1ItKV6ijJsIliqxdZCKeqmSQNQKWwGCkM6ZwJDKe7luq9plx6gDpAzg.webp',
        hard: true,
        difficulty: 'NORMAL',
    },
    {
        check: false,
        name: '카오스 감시자 칼로스',
        meso: 746000000,
        src: 'https://i.namu.wiki/i/XKVybiizrvprkaLQltvNf3XfqPB1BSn1ItKV6ijJsIliqxdZCKeqmSQNQKWwGCkM6ZwJDKe7luq9plx6gDpAzg.webp',
        hard: true,
        difficulty: 'CHAOS',
    },
    {
        check: false,
        name: '익스트림 감시자 칼로스',
        meso: 1500000000,
        src: 'https://i.namu.wiki/i/XKVybiizrvprkaLQltvNf3XfqPB1BSn1ItKV6ijJsIliqxdZCKeqmSQNQKWwGCkM6ZwJDKe7luq9plx6gDpAzg.webp',
        hard: true,
        difficulty: 'EXTREME',
        extreme: true,
    },
    {
        check: false,
        name: '익스트림 선택받은 세렌',
        meso: 1340000000,
        src: 'https://i.namu.wiki/i/DhzPskFnaHWVTfJk_Tb0GDDk7YWU8g-MS9IEau0kC03K7BKdFeZPheFglgLazh_9UuVj_jcaLdEH1L5dmM1jfQ.webp',
        hard: true,
        difficulty: 'EXTREME',
        extreme: true,
    },
    {
        check: false,
        name: '이지 카링',
        meso: 293000000,
        src: 'https://i.namu.wiki/i/ex5ViuTKPKviftIb21RyUf36qfe6yCg5O1lyfmfNFFWpurlq54GpRRcI7KdOHcAgLgrRJDcpyoBvhdzuXNzGtQ.webp',
        hard: true,
        difficulty: 'EASY',
    },
    {
        check: false,
        name: '노말 카링',
        meso: 425000000,
        src: 'https://i.namu.wiki/i/ex5ViuTKPKviftIb21RyUf36qfe6yCg5O1lyfmfNFFWpurlq54GpRRcI7KdOHcAgLgrRJDcpyoBvhdzuXNzGtQ.webp',
        hard: true,
        difficulty: 'NORMAL',
    },
    {
        check: false,
        name: '하드 카링',
        meso: 870000000,
        src: 'https://i.namu.wiki/i/ex5ViuTKPKviftIb21RyUf36qfe6yCg5O1lyfmfNFFWpurlq54GpRRcI7KdOHcAgLgrRJDcpyoBvhdzuXNzGtQ.webp',
        hard: true,
        difficulty: 'HARD',
    },
    {
        check: false,
        name: '익스트림 카링',
        meso: 1750000000,
        src: 'https://i.namu.wiki/i/ex5ViuTKPKviftIb21RyUf36qfe6yCg5O1lyfmfNFFWpurlq54GpRRcI7KdOHcAgLgrRJDcpyoBvhdzuXNzGtQ.webp',
        hard: true,
        difficulty: 'EXTREME',
        extreme: true,
    },
    {
        check: false,
        name: '노말 림보',
        meso: 600000000,
        src: 'https://i.namu.wiki/i/7xXU2wR9QNoX1rCITJqb8qrxCCYeOVVt6fSGgxxlWAcWbxlfWCXlg3JG9IL5EldpZjdVgrAbFnbJ28zfu231fw.webp',
        hard: true,
        difficulty: 'NORMAL',
    },
    {
        check: false,
        name: '하드 림보',
        meso: 1070000000,
        src: 'https://i.namu.wiki/i/7xXU2wR9QNoX1rCITJqb8qrxCCYeOVVt6fSGgxxlWAcWbxlfWCXlg3JG9IL5EldpZjdVgrAbFnbJ28zfu231fw.webp',
        hard: true,
        difficulty: 'HARD',
    },
    {
        check: false,
        name: '익스트림 스우',
        meso: 392000000,
        src: 'https://i.namu.wiki/i/ruflnxOS_pahmLa1F5ZGd0fGMayv2-2OeUsoE1f9amaqSvEabumApKDwKYiOtV1caYUhxrZ-glhPQ2cPC8ICPw.webp',
        hard: true,
        difficulty: 'EXTREME',
        extreme: true,
    },
];

interface BossItemType {
    [key : string] : string;
}


export const BossItem = [
    {name : '거공', src : 'image/거공.PNG', checked : false},
    {name : '고근' , src : 'image/고근.PNG', checked : false},
    {name : '루컨마' , src : 'image/루컨마.PNG', checked : false},
    {name : '마깃안' , src : 'image/마깃안.PNG', checked : false},
    {name : '몽벨' , src : 'image/몽벨.PNG', checked : false},
    {name : '커포링' , src : 'image/커포링.PNG', checked : false},
    {name : '블랙하트' , src : 'image/블랙하트.PNG', checked : false},
    {name : '마도서' , src : 'image/마도서.PNG', checked : false},
    {name : '창뱃' , src : 'image/창뱃.PNG', checked : false},
    {name : '데이브레이크' , src : 'image/데이브레이크.PNG', checked : false},
    {name : '트왈마' , src : 'image/트왈마.PNG', checked : false},
    {name : '가엔링' , src : 'image/가엔링.PNG', checked : false},
    {name : '에스텔라' , src : 'image/에스텔라.PNG', checked : false},
    {name : '프악공' , src : 'image/프악공.PNG', checked : false},
    {name : '프펫공' , src : 'image/프펫공.PNG', checked : false},
    {name : '매지컬' , src : 'image/매지컬.PNG', checked : false},
]